/**
 * The three things the open databases do not hand you: how big it is, what it eats, and where
 * it lives.
 *
 * GBIF knows where a species has been recorded and iNaturalist knows what it is called, but
 * neither carries a body length or a diet in a form you can read out to a five year old. So those
 * come from here: a table keyed by taxon name, looked up species first, then genus, family, order,
 * class, phylum, taking the first entry that matches. A leopard gets the leopard's length; a
 * beetle nobody has measured gets its family's, and says "ongeveer" about it.
 *
 * Every number is a typical adult, head to tail, in centimetres, taken from the ranges the usual
 * references give. They are deliberately round: this is a scale bar next to a child, not a
 * specimen label.
 */

/** typical adult length, nose to tail, in centimetres */
export const SIZE_CM = {
  // ---- mammals: the ones a child will look up first
  'Balaenoptera musculus': 2500, 'Balaenoptera physalus': 2000, 'Physeter macrocephalus': 1600,
  'Megaptera novaeangliae': 1400, 'Eubalaena glacialis': 1500, 'Orcinus orca': 700,
  'Loxodonta africana': 650, 'Elephas maximus': 600, 'Giraffa camelopardalis': 500,
  'Hippopotamus amphibius': 400, 'Ceratotherium simum': 380, 'Diceros bicornis': 350,
  'Ursus maritimus': 250, 'Ursus arctos': 220, 'Ursus americanus': 170, 'Ailuropoda melanoleuca': 150,
  'Panthera tigris': 250, 'Panthera leo': 200, 'Panthera onca': 170, 'Panthera pardus': 150,
  'Acinonyx jubatus': 130, 'Puma concolor': 140, 'Lynx lynx': 105, 'Felis catus': 50,
  'Canis lupus': 120, 'Canis familiaris': 80, 'Canis lupus familiaris': 80, 'Vulpes vulpes': 75,
  'Gorilla gorilla': 170, 'Gorilla beringei': 175, 'Pan troglodytes': 130, 'Pan paniscus': 115,
  'Pongo pygmaeus': 130, 'Pongo abelii': 130, 'Homo sapiens': 165, 'Papio anubis': 75,
  'Macaca mulatta': 50, 'Alouatta palliata': 60, 'Lemur catta': 45, 'Callithrix jacchus': 20,
  'Cervus elaphus': 200, 'Alces alces': 250, 'Rangifer tarandus': 180, 'Capreolus capreolus': 120,
  'Odocoileus virginianus': 180, 'Dama dama': 150, 'Bison bison': 300, 'Bison bonasus': 300,
  'Bos taurus': 250, 'Ovis aries': 120, 'Capra hircus': 120, 'Sus scrofa': 150,
  'Equus caballus': 240, 'Equus ferus caballus': 240, 'Equus quagga': 230, 'Equus asinus': 200,
  'Camelus dromedarius': 300, 'Camelus bactrianus': 300, 'Lama glama': 190, 'Vicugna pacos': 150,
  'Oryctolagus cuniculus': 40, 'Lepus europaeus': 60, 'Sciurus vulgaris': 22, 'Sciurus carolinensis': 25,
  'Castor fiber': 90, 'Castor canadensis': 90, 'Rattus norvegicus': 25, 'Mus musculus': 8,
  'Erinaceus europaeus': 25, 'Talpa europaea': 14, 'Meles meles': 75, 'Lutra lutra': 75,
  'Mustela erminea': 27, 'Martes martes': 50, 'Procyon lotor': 60, 'Mephitis mephitis': 55,
  'Phoca vitulina': 160, 'Halichoerus grypus': 200, 'Zalophus californianus': 200,
  'Odobenus rosmarus': 300, 'Trichechus manatus': 300, 'Tursiops truncatus': 280,
  'Macropus giganteus': 130, 'Osphranter rufus': 160, 'Phascolarctos cinereus': 75,
  'Vombatus ursinus': 100, 'Didelphis virginiana': 50, 'Ornithorhynchus anatinus': 45,
  'Tachyglossus aculeatus': 40, 'Dasypus novemcinctus': 50, 'Myrmecophaga tridactyla': 190,
  'Bradypus variegatus': 60, 'Choloepus hoffmanni': 65, 'Pteropus vampyrus': 30,
  'Suricata suricatta': 30, 'Crocuta crocuta': 130, 'Hyaena hyaena': 110, 'Lycaon pictus': 100,
  'Connochaetes taurinus': 220, 'Oryx gazella': 200, 'Gazella gazella': 110, 'Aepyceros melampus': 140,
  'Hydrochoerus hydrochaeris': 110, 'Erethizon dorsatum': 70, 'Marmota monax': 50,
  // ---- birds
  'Struthio camelus': 250, 'Dromaius novaehollandiae': 175, 'Aptenodytes forsteri': 120,
  'Pygoscelis papua': 80, 'Spheniscus demersus': 65, 'Cygnus olor': 150, 'Anser anser': 85,
  'Anas platyrhynchos': 58, 'Branta canadensis': 100, 'Ardea alba': 100, 'Ardea cinerea': 95,
  'Ciconia ciconia': 110, 'Phoenicopterus roseus': 140, 'Pelecanus onocrotalus': 160,
  'Haliaeetus leucocephalus': 90, 'Aquila chrysaetos': 85, 'Buteo buteo': 55, 'Falco peregrinus': 45,
  'Bubo bubo': 70, 'Strix aluco': 40, 'Tyto alba': 35, 'Athene noctua': 23,
  'Corvus corax': 65, 'Corvus corone': 48, 'Pica pica': 46, 'Garrulus glandarius': 34,
  'Passer domesticus': 15, 'Turdus merula': 25, 'Erithacus rubecula': 14, 'Parus major': 14,
  'Cyanistes caeruleus': 12, 'Hirundo rustica': 18, 'Apus apus': 17, 'Columba livia': 33,
  'Picus viridis': 32, 'Dendrocopos major': 23, 'Alcedo atthis': 17, 'Upupa epops': 27,
  'Cuculus canorus': 33, 'Larus argentatus': 60, 'Sterna hirundo': 35, 'Fratercula arctica': 29,
  'Gallus gallus': 60, 'Meleagris gallopavo': 110, 'Phasianus colchicus': 80, 'Pavo cristatus': 110,
  'Ara macao': 85, 'Psittacus erithacus': 33, 'Melopsittacus undulatus': 18,
  'Archilochus colubris': 9, 'Grus grus': 115, 'Vanellus vanellus': 30, 'Sturnus vulgaris': 21,
  // ---- fish, sharks and rays
  'Rhincodon typus': 1000, 'Cetorhinus maximus': 800, 'Carcharodon carcharias': 450,
  'Galeocerdo cuvier': 400, 'Sphyrna mokarran': 450, 'Prionace glauca': 300,
  'Carcharhinus leucas': 240, 'Squalus acanthias': 100, 'Scyliorhinus canicula': 75,
  'Manta birostris': 500, 'Mobula birostris': 500, 'Dasyatis pastinaca': 140, 'Raja clavata': 90,
  'Thunnus thynnus': 250, 'Xiphias gladius': 300, 'Istiophorus platypterus': 300,
  'Mola mola': 250, 'Salmo salar': 100, 'Salmo trutta': 50, 'Oncorhynchus mykiss': 55,
  'Esox lucius': 90, 'Cyprinus carpio': 60, 'Carassius auratus': 15, 'Anguilla anguilla': 80,
  'Gadus morhua': 90, 'Pleuronectes platessa': 45, 'Clupea harengus': 30, 'Scomber scombrus': 35,
  'Hippocampus hippocampus': 12, 'Amphiprion ocellaris': 9, 'Betta splendens': 7,
  'Perca fluviatilis': 30, 'Gasterosteus aculeatus': 7, 'Lepomis macrochirus': 20,
  'Micropterus salmoides': 45, 'Pterois volitans': 35, 'Chelmon rostratus': 18,
  // ---- reptiles
  'Crocodylus porosus': 500, 'Crocodylus niloticus': 450, 'Alligator mississippiensis': 400,
  'Caiman crocodilus': 220, 'Chelonia mydas': 110, 'Dermochelys coriacea': 180,
  'Caretta caretta': 95, 'Chelonoidis niger': 120, 'Testudo hermanni': 22, 'Trachemys scripta': 25,
  'Varanus komodoensis': 260, 'Varanus niloticus': 150, 'Iguana iguana': 150,
  'Chamaeleo chamaeleon': 25, 'Gekko gecko': 30, 'Lacerta agilis': 20, 'Podarcis muralis': 18,
  'Python bivittatus': 400, 'Python regius': 130, 'Boa constrictor': 250, 'Eunectes murinus': 500,
  'Naja naja': 180, 'Ophiophagus hannah': 400, 'Crotalus atrox': 130, 'Vipera berus': 60,
  'Natrix natrix': 100, 'Thamnophis sirtalis': 70,
  // ---- amphibians
  'Rana temporaria': 9, 'Pelophylax ridibundus': 12, 'Bufo bufo': 12, 'Bufo spinosus': 12,
  'Hyla arborea': 4, 'Dendrobates auratus': 4, 'Phyllobates terribilis': 5,
  'Lithobates catesbeianus': 18, 'Ceratophrys ornata': 12, 'Ambystoma mexicanum': 25,
  'Salamandra salamandra': 22, 'Lissotriton vulgaris': 10, 'Triturus cristatus': 15,
  'Andrias japonicus': 140,
  // ---- insects, butterflies, spiders (wingspan for the fliers)
  'Danaus plexippus': 10, 'Papilio machaon': 8, 'Vanessa atalanta': 6, 'Aglais io': 6,
  'Pieris rapae': 5, 'Morpho peleides': 13, 'Attacus atlas': 26, 'Saturnia pyri': 15,
  'Apis mellifera': 1.4, 'Bombus terrestris': 2.2, 'Vespa crabro': 3.5, 'Vespula vulgaris': 1.7,
  'Formica rufa': 0.9, 'Lucanus cervus': 7, 'Dynastes hercules': 15, 'Coccinella septempunctata': 0.7,
  'Melolontha melolontha': 3, 'Gryllus campestris': 2.5, 'Locusta migratoria': 5,
  'Mantis religiosa': 7, 'Anax imperator': 11, 'Libellula depressa': 7, 'Calopteryx splendens': 6,
  'Gerris lacustris': 1.5, 'Cicada orni': 4, 'Musca domestica': 0.8, 'Culex pipiens': 0.6,
  'Araneus diadematus': 1.6, 'Argiope bruennichi': 2.5, 'Theraphosa blondi': 12,
  'Latrodectus mactans': 1.2, 'Pholcus phalangioides': 1, 'Salticus scenicus': 0.7,
  'Scorpio maurus': 7, 'Pandinus imperator': 18, 'Ixodes ricinus': 0.4,
  // ---- sea creatures
  'Architeuthis dux': 1000, 'Octopus vulgaris': 90, 'Sepia officinalis': 40, 'Loligo vulgaris': 40,
  'Nautilus pompilius': 20, 'Helix pomatia': 5, 'Cornu aspersum': 4, 'Arion rufus': 12,
  'Mytilus edulis': 8, 'Ostrea edulis': 10, 'Pecten maximus': 15, 'Tridacna gigas': 120,
  'Homarus gammarus': 50, 'Cancer pagurus': 25, 'Carcinus maenas': 8, 'Pagurus bernhardus': 10,
  'Birgus latro': 40, 'Palaemon serratus': 10, 'Asterias rubens': 25, 'Echinus esculentus': 15,
  'Aurelia aurita': 30, 'Cyanea capillata': 100, 'Physalia physalis': 30,
  'Lumbricus terrestris': 20, 'Hirudo medicinalis': 12, 'Limulus polyphemus': 50,

  // ---- and then the fall-backs, from the family upwards
  Balaenopteridae: 1500, Delphinidae: 250, Phocoenidae: 160, Physeteridae: 1100,
  Elephantidae: 600, Giraffidae: 450, Rhinocerotidae: 360, Hippopotamidae: 380,
  Ursidae: 190, Felidae: 90, Canidae: 90, Mustelidae: 55, Procyonidae: 60, Viverridae: 60,
  Herpestidae: 40, Hyaenidae: 120, Otariidae: 190, Phocidae: 160, Odobenidae: 300,
  Hominidae: 140, Hylobatidae: 55, Cercopithecidae: 60, Atelidae: 55, Cebidae: 35, Lemuridae: 40,
  Cervidae: 150, Bovidae: 150, Suidae: 130, Equidae: 220, Camelidae: 220, Tayassuidae: 100,
  Leporidae: 45, Sciuridae: 28, Castoridae: 90, Cricetidae: 12, Muridae: 12, Gliridae: 12,
  Caviidae: 30, Erethizontidae: 65, Chinchillidae: 30, Dipodidae: 12, Geomyidae: 20,
  Erinaceidae: 24, Talpidae: 14, Soricidae: 8, Vespertilionidae: 9, Pteropodidae: 25,
  Macropodidae: 110, Phalangeridae: 45, Dasyuridae: 25, Didelphidae: 40, Phascolarctidae: 75,
  Myrmecophagidae: 120, Bradypodidae: 60, Dasypodidae: 45, Manidae: 60,
  Struthionidae: 250, Casuariidae: 160, Spheniscidae: 70, Anatidae: 55, Ardeidae: 75,
  Ciconiidae: 105, Threskiornithidae: 75, Phoenicopteridae: 130, Pelecanidae: 150,
  Phalacrocoracidae: 80, Sulidae: 85, Procellariidae: 45, Diomedeidae: 110,
  Accipitridae: 65, Falconidae: 40, Pandionidae: 60, Strigidae: 40, Tytonidae: 35,
  Corvidae: 40, Paridae: 13, Fringillidae: 14, Passeridae: 15, Emberizidae: 16,
  Turdidae: 22, Muscicapidae: 14, Sylviidae: 13, Hirundinidae: 17, Motacillidae: 17,
  Sturnidae: 21, Laniidae: 19, Alaudidae: 17, Troglodytidae: 10, Certhiidae: 12, Sittidae: 14,
  Picidae: 25, Apodidae: 16, Trochilidae: 10, Alcedinidae: 20, Meropidae: 27, Coraciidae: 30,
  Columbidae: 32, Cuculidae: 32, Psittacidae: 35, Cacatuidae: 40, Ramphastidae: 50,
  Phasianidae: 55, Anhimidae: 85, Rallidae: 32, Gruidae: 110, Otididae: 90,
  Scolopacidae: 27, Charadriidae: 22, Laridae: 42, Sternidae: 33, Alcidae: 32,
  Tyrannidae: 16, Parulidae: 12, Icteridae: 24, Cardinalidae: 18, Thraupidae: 14,
  Rhincodontidae: 900, Lamnidae: 350, Carcharhinidae: 200, Sphyrnidae: 300,
  Scyliorhinidae: 70, Squalidae: 90, Myliobatidae: 180, Dasyatidae: 120, Rajidae: 80,
  Salmonidae: 55, Cyprinidae: 25, Esocidae: 80, Percidae: 30, Gadidae: 70, Clupeidae: 25,
  Scombridae: 80, Serranidae: 50, Pomacentridae: 10, Labridae: 25, Chaetodontidae: 15,
  Acanthuridae: 25, Scaridae: 35, Syngnathidae: 15, Anguillidae: 70, Cichlidae: 18,
  Gobiidae: 8, Blenniidae: 10, Pleuronectidae: 40, Soleidae: 30, Sciaenidae: 45,
  Siluridae: 80, Ictaluridae: 40, Loricariidae: 25, Characidae: 8, Poeciliidae: 5,
  Crocodylidae: 380, Alligatoridae: 300, Testudinidae: 40, Emydidae: 22, Cheloniidae: 100,
  Trionychidae: 40, Varanidae: 120, Iguanidae: 90, Agamidae: 30, Chamaeleonidae: 25,
  Gekkonidae: 15, Lacertidae: 20, Scincidae: 20, Teiidae: 40, Phrynosomatidae: 15,
  Pythonidae: 300, Boidae: 250, Colubridae: 100, Viperidae: 80, Elapidae: 150,
  Ranidae: 8, Bufonidae: 9, Hylidae: 5, Dendrobatidae: 3, Leptodactylidae: 6,
  Pipidae: 8, Microhylidae: 4, Salamandridae: 14, Ambystomatidae: 20, Plethodontidae: 10,
  Cryptobranchidae: 110, Sirenidae: 60,
  Papilionidae: 9, Nymphalidae: 6, Pieridae: 5, Lycaenidae: 3, Hesperiidae: 3, Riodinidae: 3,
  Saturniidae: 12, Sphingidae: 9, Noctuidae: 4, Geometridae: 3, Erebidae: 4, Arctiidae: 4,
  Apidae: 1.5, Vespidae: 2, Formicidae: 0.8, Ichneumonidae: 2, Halictidae: 1,
  Scarabaeidae: 2.5, Carabidae: 2, Cerambycidae: 3, Coccinellidae: 0.7, Curculionidae: 1,
  Chrysomelidae: 0.8, Lucanidae: 5, Staphylinidae: 1, Elateridae: 1.5, Buprestidae: 1.5,
  Libellulidae: 7, Aeshnidae: 10, Calopterygidae: 6, Coenagrionidae: 4, Gomphidae: 7,
  Acrididae: 4, Tettigoniidae: 4, Gryllidae: 2, Mantidae: 7, Blattidae: 3,
  Syrphidae: 1.2, Tabanidae: 1.8, Culicidae: 0.6, Calliphoridae: 1, Tipulidae: 3,
  Cicadidae: 3.5, Pentatomidae: 1.4, Reduviidae: 1.8, Cercopidae: 0.6, Aphididae: 0.3,
  Araneidae: 1.4, Salticidae: 0.8, Lycosidae: 1.4, Theridiidae: 0.7, Thomisidae: 0.9,
  Theraphosidae: 8, Sparassidae: 3, Agelenidae: 1.4, Pholcidae: 1, Tetragnathidae: 1.1,
  Scorpionidae: 10, Buthidae: 6, Ixodidae: 0.4,
  Octopodidae: 70, Sepiidae: 30, Loliginidae: 30, Nautilidae: 20,
  Helicidae: 4, Arionidae: 9, Limacidae: 12, Lymnaeidae: 3, Littorinidae: 2, Muricidae: 6,
  Mytilidae: 7, Ostreidae: 9, Pectinidae: 12, Cardiidae: 6, Veneridae: 5, Unionidae: 9,
  Nephropidae: 45, Cancridae: 20, Portunidae: 12, Grapsidae: 5, Paguridae: 8,
  Penaeidae: 15, Palaemonidae: 8, Gammaridae: 1.5, Oniscidae: 1.5, Asellidae: 1,
  Asteriidae: 22, Echinidae: 12, Holothuriidae: 25, Ophiuridae: 12,
  Ulmaridae: 28, Cyaneidae: 60, Pelagiidae: 25, Acroporidae: 40,
  Lumbricidae: 14, Nereididae: 10, Hirudinidae: 10,
  // ---- and finally the whole class, for anything the table has never heard of
  Cetacea: 500, Primates: 70, Carnivora: 90, Artiodactyla: 150, Rodentia: 20, Chiroptera: 10,
  Perissodactyla: 250, Proboscidea: 600, Lagomorpha: 45, Eulipotyphla: 14, Diprotodontia: 70,
  Mammalia: 60, Aves: 25, Reptilia: 50, Squamata: 45, Testudines: 40, Crocodylia: 350,
  Amphibia: 9, Anura: 7, Caudata: 15, Chondrichthyes: 150, Actinopterygii: 30,
  Lepidoptera: 5, Coleoptera: 1.5, Hymenoptera: 1.2, Diptera: 1, Hemiptera: 1,
  Odonata: 6, Orthoptera: 3, Blattodea: 2.5, Mantodea: 6, Neuroptera: 2,
  Insecta: 1.5, Arachnida: 1.2, Araneae: 1.2, Scorpiones: 7,
  Cephalopoda: 40, Gastropoda: 4, Bivalvia: 7, Mollusca: 6,
  Malacostraca: 8, Decapoda: 12, Crustacea: 6, Echinodermata: 15, Cnidaria: 20, Annelida: 10,
  Animalia: 10,
};

/** what it eats: one of meat, fish, plants, insects, omnivore, nectar, plankton, wood, blood */
export const DIET = {
  'Ailuropoda melanoleuca': 'plants', 'Ursus maritimus': 'meat', 'Ursus arctos': 'omnivore',
  'Rhincodon typus': 'plankton', 'Cetorhinus maximus': 'plankton', 'Mobula birostris': 'plankton',
  'Balaenoptera musculus': 'plankton', 'Megaptera novaeangliae': 'plankton',
  'Phoenicopterus roseus': 'plankton', 'Sus scrofa': 'omnivore', 'Homo sapiens': 'omnivore',
  'Gorilla gorilla': 'plants', 'Gorilla beringei': 'plants', 'Pan troglodytes': 'omnivore',
  'Orcinus orca': 'meat', 'Physeter macrocephalus': 'fish', 'Erinaceus europaeus': 'insects',
  'Hippopotamus amphibius': 'plants', 'Lutra lutra': 'fish', 'Meles meles': 'omnivore',
  Felidae: 'meat', Canidae: 'meat', Mustelidae: 'meat', Hyaenidae: 'meat', Viverridae: 'omnivore',
  Ursidae: 'omnivore', Procyonidae: 'omnivore', Herpestidae: 'insects', Mephitidae: 'omnivore',
  Otariidae: 'fish', Phocidae: 'fish', Odobenidae: 'fish', Delphinidae: 'fish',
  Balaenopteridae: 'plankton', Physeteridae: 'fish', Phocoenidae: 'fish',
  Bovidae: 'plants', Cervidae: 'plants', Giraffidae: 'plants', Equidae: 'plants',
  Camelidae: 'plants', Rhinocerotidae: 'plants', Elephantidae: 'plants', Hippopotamidae: 'plants',
  Suidae: 'omnivore', Leporidae: 'plants', Sciuridae: 'plants', Castoridae: 'wood',
  Muridae: 'omnivore', Cricetidae: 'plants', Caviidae: 'plants', Erethizontidae: 'plants',
  Hominidae: 'omnivore', Cercopithecidae: 'omnivore', Hylobatidae: 'plants', Lemuridae: 'plants',
  Atelidae: 'plants', Cebidae: 'omnivore', Callitrichidae: 'omnivore',
  Erinaceidae: 'insects', Talpidae: 'insects', Soricidae: 'insects', Vespertilionidae: 'insects',
  Pteropodidae: 'plants', Myrmecophagidae: 'insects', Manidae: 'insects', Dasypodidae: 'insects',
  Macropodidae: 'plants', Phascolarctidae: 'plants', Dasyuridae: 'meat', Didelphidae: 'omnivore',
  Accipitridae: 'meat', Falconidae: 'meat', Strigidae: 'meat', Tytonidae: 'meat',
  Pandionidae: 'fish', Ardeidae: 'fish', Ciconiidae: 'fish', Pelecanidae: 'fish',
  Phalacrocoracidae: 'fish', Sulidae: 'fish', Alcedinidae: 'fish', Laridae: 'omnivore',
  Sternidae: 'fish', Alcidae: 'fish', Spheniscidae: 'fish', Procellariidae: 'fish',
  Diomedeidae: 'fish', Gaviidae: 'fish', Podicipedidae: 'fish', Anhingidae: 'fish',
  Anatidae: 'plants', Rallidae: 'omnivore', Gruidae: 'omnivore', Scolopacidae: 'insects',
  Charadriidae: 'insects', Phasianidae: 'omnivore', Columbidae: 'plants', Struthionidae: 'plants',
  Casuariidae: 'plants', Psittacidae: 'plants', Cacatuidae: 'plants', Ramphastidae: 'plants',
  Fringillidae: 'plants', Passeridae: 'plants', Emberizidae: 'plants', Cardinalidae: 'plants',
  Corvidae: 'omnivore', Sturnidae: 'omnivore', Paridae: 'insects', Turdidae: 'omnivore',
  Muscicapidae: 'insects', Sylviidae: 'insects', Hirundinidae: 'insects', Apodidae: 'insects',
  Motacillidae: 'insects', Picidae: 'insects', Certhiidae: 'insects', Sittidae: 'insects',
  Troglodytidae: 'insects', Tyrannidae: 'insects', Parulidae: 'insects', Laniidae: 'insects',
  Alaudidae: 'omnivore', Cuculidae: 'insects', Meropidae: 'insects', Coraciidae: 'insects',
  Trochilidae: 'nectar', Nectariniidae: 'nectar', Thraupidae: 'plants', Icteridae: 'omnivore',
  Lamnidae: 'meat', Carcharhinidae: 'fish', Sphyrnidae: 'fish', Scyliorhinidae: 'fish',
  Squalidae: 'fish', Dasyatidae: 'fish', Rajidae: 'fish', Myliobatidae: 'plankton',
  Esocidae: 'fish', Salmonidae: 'insects', Percidae: 'fish', Gadidae: 'fish', Scombridae: 'fish',
  Serranidae: 'fish', Sciaenidae: 'fish', Siluridae: 'fish', Ictaluridae: 'omnivore',
  Cyprinidae: 'omnivore', Clupeidae: 'plankton', Cichlidae: 'omnivore', Labridae: 'omnivore',
  Pomacentridae: 'plankton', Chaetodontidae: 'omnivore', Acanthuridae: 'plants', Scaridae: 'plants',
  Syngnathidae: 'plankton', Anguillidae: 'fish', Gobiidae: 'insects', Blenniidae: 'plants',
  Loricariidae: 'plants', Characidae: 'omnivore', Poeciliidae: 'omnivore', Pleuronectidae: 'fish',
  Crocodylidae: 'meat', Alligatoridae: 'meat', Pythonidae: 'meat', Boidae: 'meat',
  Colubridae: 'meat', Viperidae: 'meat', Elapidae: 'meat', Varanidae: 'meat',
  Testudinidae: 'plants', Emydidae: 'omnivore', Cheloniidae: 'plants', Trionychidae: 'meat',
  Iguanidae: 'plants', Agamidae: 'insects', Chamaeleonidae: 'insects', Gekkonidae: 'insects',
  Lacertidae: 'insects', Scincidae: 'insects', Teiidae: 'insects', Phrynosomatidae: 'insects',
  Ranidae: 'insects', Bufonidae: 'insects', Hylidae: 'insects', Dendrobatidae: 'insects',
  Salamandridae: 'insects', Ambystomatidae: 'insects', Plethodontidae: 'insects',
  Pipidae: 'insects', Cryptobranchidae: 'fish',
  Papilionidae: 'nectar', Nymphalidae: 'nectar', Pieridae: 'nectar', Lycaenidae: 'nectar',
  Hesperiidae: 'nectar', Riodinidae: 'nectar', Sphingidae: 'nectar', Saturniidae: 'nectar',
  Noctuidae: 'nectar', Geometridae: 'nectar', Erebidae: 'nectar', Apidae: 'nectar',
  Halictidae: 'nectar', Andrenidae: 'nectar', Megachilidae: 'nectar', Syrphidae: 'nectar',
  Vespidae: 'insects', Formicidae: 'omnivore', Ichneumonidae: 'insects',
  Coccinellidae: 'insects', Carabidae: 'insects', Staphylinidae: 'insects', Mantidae: 'insects',
  Libellulidae: 'insects', Aeshnidae: 'insects', Calopterygidae: 'insects', Coenagrionidae: 'insects',
  Cerambycidae: 'wood', Lucanidae: 'wood', Buprestidae: 'wood', Scolytidae: 'wood',
  Curculionidae: 'plants', Chrysomelidae: 'plants', Scarabaeidae: 'plants', Elateridae: 'plants',
  Acrididae: 'plants', Tettigoniidae: 'omnivore', Gryllidae: 'omnivore', Blattidae: 'omnivore',
  Aphididae: 'plants', Cicadidae: 'plants', Pentatomidae: 'plants', Cercopidae: 'plants',
  Reduviidae: 'insects', Culicidae: 'blood', Tabanidae: 'blood', Siphonaptera: 'blood',
  Ixodidae: 'blood', Calliphoridae: 'omnivore', Muscidae: 'omnivore', Tipulidae: 'plants',
  Araneae: 'insects', Arachnida: 'insects', Scorpiones: 'insects',
  Octopodidae: 'meat', Sepiidae: 'meat', Loliginidae: 'fish', Nautilidae: 'meat',
  Helicidae: 'plants', Arionidae: 'plants', Limacidae: 'plants', Littorinidae: 'plants',
  Muricidae: 'meat', Mytilidae: 'plankton', Ostreidae: 'plankton', Pectinidae: 'plankton',
  Cardiidae: 'plankton', Veneridae: 'plankton', Unionidae: 'plankton', Bivalvia: 'plankton',
  Nephropidae: 'omnivore', Cancridae: 'omnivore', Portunidae: 'omnivore', Paguridae: 'omnivore',
  Penaeidae: 'omnivore', Asteriidae: 'meat', Echinidae: 'plants', Holothuriidae: 'plankton',
  Cnidaria: 'plankton', Lumbricidae: 'plants', Hirudinidae: 'blood',
  // class-level last resort
  Carnivora: 'meat', Artiodactyla: 'plants', Perissodactyla: 'plants', Rodentia: 'plants',
  Chiroptera: 'insects', Primates: 'omnivore', Lagomorpha: 'plants', Eulipotyphla: 'insects',
  Cetacea: 'fish', Aves: 'omnivore', Mammalia: 'omnivore', Reptilia: 'meat', Squamata: 'insects',
  Amphibia: 'insects', Chondrichthyes: 'fish', Actinopterygii: 'omnivore',
  Lepidoptera: 'nectar', Coleoptera: 'plants', Hymenoptera: 'omnivore', Diptera: 'omnivore',
  Hemiptera: 'plants', Odonata: 'insects', Orthoptera: 'plants', Insecta: 'plants',
  Gastropoda: 'plants', Cephalopoda: 'meat', Mollusca: 'plants', Malacostraca: 'omnivore',
  Echinodermata: 'plankton', Annelida: 'plants', Animalia: 'omnivore',
};

/** where you find it: sea, coast, freshwater, forest, grass, desert, mountain, polar, town, air, underground */
export const HABITAT = {
  Cetacea: 'sea', Pinnipedia: 'coast', Otariidae: 'coast', Phocidae: 'coast', Odobenidae: 'polar',
  Sirenia: 'sea', 'Ursus maritimus': 'polar', 'Aptenodytes forsteri': 'polar',
  Spheniscidae: 'coast', Procellariidae: 'sea', Diomedeidae: 'sea', Sulidae: 'sea',
  Alcidae: 'sea', Laridae: 'coast', Sternidae: 'coast', Phalacrocoracidae: 'coast',
  Pelecanidae: 'coast', Scolopacidae: 'coast', Charadriidae: 'coast', Haematopodidae: 'coast',
  Ardeidae: 'freshwater', Ciconiidae: 'freshwater', Anatidae: 'freshwater', Rallidae: 'freshwater',
  Gruidae: 'freshwater', Podicipedidae: 'freshwater', Gaviidae: 'freshwater',
  Alcedinidae: 'freshwater', Phoenicopteridae: 'freshwater',
  Accipitridae: 'air', Falconidae: 'air', Apodidae: 'air', Hirundinidae: 'air',
  Strigidae: 'forest', Tytonidae: 'grass', Picidae: 'forest', Paridae: 'forest',
  Corvidae: 'forest', Fringillidae: 'forest', Turdidae: 'forest', Muscicapidae: 'forest',
  Sylviidae: 'forest', Sittidae: 'forest', Certhiidae: 'forest', Troglodytidae: 'forest',
  Psittacidae: 'forest', Ramphastidae: 'forest', Trochilidae: 'forest', Cuculidae: 'forest',
  Columbidae: 'town', Passeridae: 'town', Sturnidae: 'town', Hirundinidae2: 'town',
  Alaudidae: 'grass', Motacillidae: 'grass', Emberizidae: 'grass', Phasianidae: 'grass',
  Struthionidae: 'grass', Otididae: 'grass', Casuariidae: 'forest',
  Chondrichthyes: 'sea', Elasmobranchii: 'sea', Actinopterygii: 'sea',
  Salmonidae: 'freshwater', Cyprinidae: 'freshwater', Esocidae: 'freshwater',
  Percidae: 'freshwater', Ictaluridae: 'freshwater', Siluridae: 'freshwater',
  Cichlidae: 'freshwater', Poeciliidae: 'freshwater', Characidae: 'freshwater',
  Loricariidae: 'freshwater', Centrarchidae: 'freshwater', Anguillidae: 'freshwater',
  Crocodylidae: 'freshwater', Alligatoridae: 'freshwater', Cheloniidae: 'sea',
  Dermochelyidae: 'sea', Emydidae: 'freshwater', Trionychidae: 'freshwater',
  Testudinidae: 'grass', Varanidae: 'forest', Iguanidae: 'forest', Chamaeleonidae: 'forest',
  Gekkonidae: 'forest', Agamidae: 'desert', Phrynosomatidae: 'desert', Lacertidae: 'grass',
  Scincidae: 'grass', Pythonidae: 'forest', Boidae: 'forest', Colubridae: 'grass',
  Viperidae: 'grass', Elapidae: 'grass', Hydrophiinae: 'sea',
  Amphibia: 'freshwater', Anura: 'freshwater', Caudata: 'freshwater', Hylidae: 'forest',
  Dendrobatidae: 'forest', Bufonidae: 'forest', Plethodontidae: 'forest',
  Felidae: 'forest', Canidae: 'forest', Ursidae: 'forest', Mustelidae: 'forest',
  'Lutra lutra': 'freshwater', Lutrinae: 'freshwater', Castoridae: 'freshwater',
  Procyonidae: 'forest', Hyaenidae: 'grass', Herpestidae: 'grass',
  Bovidae: 'grass', Cervidae: 'forest', Giraffidae: 'grass', Equidae: 'grass',
  Camelidae: 'desert', Elephantidae: 'grass', Rhinocerotidae: 'grass',
  Hippopotamidae: 'freshwater', Suidae: 'forest',
  Hominidae: 'forest', Cercopithecidae: 'forest', Hylobatidae: 'forest', Lemuridae: 'forest',
  Atelidae: 'forest', Cebidae: 'forest', Callitrichidae: 'forest',
  Sciuridae: 'forest', Muridae: 'town', Cricetidae: 'grass', Leporidae: 'grass',
  Caviidae: 'grass', Chinchillidae: 'mountain', Dipodidae: 'desert', Geomyidae: 'underground',
  Talpidae: 'underground', Soricidae: 'forest', Erinaceidae: 'town',
  Vespertilionidae: 'air', Pteropodidae: 'forest', Macropodidae: 'grass',
  Phascolarctidae: 'forest', Dasyuridae: 'forest', Didelphidae: 'forest',
  Caprinae: 'mountain', 'Capra ibex': 'mountain', 'Rupicapra rupicapra': 'mountain',
  // the famous ones, where the family's usual home is not theirs
  'Panthera leo': 'grass', 'Acinonyx jubatus': 'grass', 'Crocuta crocuta': 'grass',
  'Lycaon pictus': 'grass', 'Suricata suricatta': 'desert', 'Vulpes zerda': 'desert',
  'Vulpes lagopus': 'polar', 'Ursus maritimus': 'polar', 'Panthera uncia': 'mountain',
  'Canis lupus': 'forest', 'Ailuropoda melanoleuca': 'forest', 'Panthera tigris': 'forest',
  'Hippopotamus amphibius': 'freshwater', 'Loxodonta africana': 'grass',
  'Ceratotherium simum': 'grass', 'Equus quagga': 'grass', 'Giraffa camelopardalis': 'grass',
  'Camelus dromedarius': 'desert', 'Camelus bactrianus': 'desert', 'Vicugna pacos': 'mountain',
  'Lama glama': 'mountain', 'Rangifer tarandus': 'polar', 'Alces alces': 'forest',
  'Aptenodytes forsteri': 'polar', 'Struthio camelus': 'grass', 'Phoenicopterus roseus': 'freshwater',
  'Varanus komodoensis': 'grass', 'Chelonoidis niger': 'grass',
  Papilionidae: 'grass', Nymphalidae: 'grass', Pieridae: 'grass', Lycaenidae: 'grass',
  Hesperiidae: 'grass', Sphingidae: 'grass', Saturniidae: 'forest', Noctuidae: 'grass',
  Geometridae: 'forest', Erebidae: 'forest',
  Apidae: 'grass', Vespidae: 'town', Formicidae: 'underground', Syrphidae: 'grass',
  Libellulidae: 'freshwater', Aeshnidae: 'freshwater', Calopterygidae: 'freshwater',
  Coenagrionidae: 'freshwater', Gomphidae: 'freshwater', Gerridae: 'freshwater',
  Dytiscidae: 'freshwater', Culicidae: 'freshwater', Tipulidae: 'grass',
  Cerambycidae: 'forest', Lucanidae: 'forest', Buprestidae: 'forest', Scarabaeidae: 'grass',
  Carabidae: 'forest', Coccinellidae: 'grass', Curculionidae: 'grass', Chrysomelidae: 'grass',
  Acrididae: 'grass', Tettigoniidae: 'grass', Gryllidae: 'grass', Mantidae: 'grass',
  Blattidae: 'town', Cicadidae: 'forest', Aphididae: 'grass', Pentatomidae: 'grass',
  Araneidae: 'grass', Salticidae: 'grass', Lycosidae: 'grass', Theridiidae: 'town',
  Pholcidae: 'town', Agelenidae: 'town', Theraphosidae: 'forest', Sparassidae: 'forest',
  Scorpiones: 'desert', Ixodidae: 'grass',
  Cephalopoda: 'sea', Bivalvia: 'sea', Mytilidae: 'coast', Ostreidae: 'coast',
  Littorinidae: 'coast', Helicidae: 'town', Arionidae: 'town', Limacidae: 'town',
  Lymnaeidae: 'freshwater', Planorbidae: 'freshwater', Unionidae: 'freshwater',
  Malacostraca: 'sea', Decapoda: 'sea', Nephropidae: 'sea', Cancridae: 'coast',
  Portunidae: 'coast', Grapsidae: 'coast', Paguridae: 'coast', Oniscidea: 'town',
  Gammaridae: 'freshwater', Asellidae: 'freshwater',
  Echinodermata: 'sea', Cnidaria: 'sea', Porifera: 'sea', Anthozoa: 'sea',
  Lumbricidae: 'underground', Annelida: 'underground', Hirudinidae: 'freshwater',
  Mammalia: 'forest', Aves: 'forest', Reptilia: 'grass', Insecta: 'grass',
  Arachnida: 'grass', Mollusca: 'sea', Animalia: 'forest',
};

/**
 * Walk up the family tree until the table knows something. The chain runs species, genus, then
 * every ancestor iNaturalist gave us, biggest rank last.
 */
export function lookUp(table, chain) {
  for (const name of chain) {
    const v = table[name];
    if (v !== undefined) return v;
  }
  return undefined;
}
